### ISSUE TITLE
IF hidpi is specified for @2x retina, @1x gets broken

### ISSUE THREAD

**Issue by edusantosdev** [tylergaw/jribbble#13] opened 2016-07-12 01:22 UTC
Hi,

Thanks a lot for this script, this is exactly what I've been looking for lately.

It seems that when I specify "images + hidpi" I get the @2x shots imported/loaded, but the @1x shots get broken.

<img width="533" alt="screen shot 2016-07-12 at 02 19 29" src="https://cloud.githubusercontent.com/assets/1864559/16752182/3f4a0ce0-47d7-11e6-9f3a-2bff177d1775.png">
<img width="608" alt="screen shot 2016-07-12 at 02 20 00" src="https://cloud.githubusercontent.com/assets/1864559/16752186/41240cc8-47d7-11e6-8b24-e1b9507fe83f.png">

I'm wondering if there is anything that can be done to fix this somehow. Or at least HIDE the @1x shots?

(I'm super raw in JS, my apologies for my "n00biness". :)

**Comment by tylergaw** [comment] 2016-07-12 01:41
@edusantosdev Hey. So this isn't an issue with Jribbble or the API, but an issue with the code used to display the shots.

The problem is this line here:

```javascript
html.push('<img src="' + shot.images.hidpi + '">');
```

that assumes that every one of Andy's shots has a hi dpi version available. Taking a quick look, we'll see that's not the case (example: https://dribbble.com/shots/905424-Tumblr-NSFW-Switch only has a normal version)

There are two approaches you could take. One, only display shots that have a hi dpi version. That's not terrible, but doesn't seem like the best approach. The other approach would be to display a hi dpi version if available and if not fall back to the normal size.

Here's a modified snippet of code that would accomplish that:

```javascript
shots.forEach(function(shot) {
  // Store the images in a variable for later use and less typing.
  var images = shot.images;
    
  // If a hidpi image is available use that, if not fall back to the normal image
  var img = (images.hidpi) ? images.hidpi : images.normal;
    
  html.push('<li class="shots--shot">');
  html.push('<a href="' + shot.html_url + '" target="_blank">');

  // Use the img variable as the src attribute value
  html.push('<img src="' + img + '">');
  html.push('</a></li>');
});
```

And here's a working example of that code http://codepen.io/tylergaw/pen/XKzXJq?editors=1010

Let me know if this does what you need it to.

**Comment by tylergaw** [comment] 2016-07-12 02:04
Also, just to clarify one bit of new code there in case you're not familiar with it. This line:

```javascript
var img = (images.hidpi) ? images.hidpi : images.normal;
```

uses a [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) Its a shortcut for an if/else statement. Another way we could write that same line of code would be:

```javascript
var img = '';

if (images.hidpi) {
  img = images.hidpi;
} else {
  img =  images.normal;
}
```

Same result as the ternary operator, but more lines of code. Either works fine, use the one that is most clear to you.

**Comment by edusantosdev** [comment] 2016-07-12 02:35
Wow! @tylergaw You're great! That does actually make sense, I love the fact that you provided explanations to the solutions.

I like the simplicity / efficiency of the ternary operator (just learnt something new today!). Although the if else statement feels more clear though.

This is what makes great teachers! Huge kudos!

- Eduardo

**Comment by tylergaw** [comment] 2016-07-12 03:57
Excellent @edusantosdev! Glad I could help out.

I'm gonna go ahead and close this issue.

**Closed by tylergaw** 2016-07-12 03:57 UTC
